'use client';
import { useEffect, useRef, useState } from 'react';
import { ROUNDS,newRun,tick,act,signal } from './rules.js';
import {createArena} from './scene.js';
import './arena.css';
export default function Arena(){
 const mount=useRef(null),run=useRef(newRun()),keys=useRef({}),move=useRef({x:0,z:0});const [s,setS]=useState({...run.current}),[paused,pause]=useState(false),[error,setError]=useState(''),[muted,mute]=useState(false);const pausedRef=useRef(false),sound=useRef(null),lastSignal=useRef('');
 function beep(f=440){if(muted)return;try{sound.current??=new AudioContext();sound.current.resume();const o=sound.current.createOscillator(),g=sound.current.createGain();o.frequency.value=f;g.gain.setValueAtTime(0.045,sound.current.currentTime);g.gain.exponentialRampToValueAtTime(0.001,sound.current.currentTime+0.14);o.connect(g);g.connect(sound.current.destination);o.start();o.stop(sound.current.currentTime+0.15);}catch{}}
 const beepRef=useRef(beep);beepRef.current=beep;
 function start(round=0,practice=false){run.current=newRun(round,practice);setS({...run.current});keys.current={};move.current={x:0,z:0};}
 function action(v){beep(500);act(run.current,v);setS({...run.current});}
 useEffect(()=>{let dispose;try{let elapsed=0;dispose=createArena(mount.current,()=>run.current,dt=>{const r=run.current;if(!pausedRef.current){const k=keys.current;const x=move.current.x+(k.d||k.ArrowRight?1:0)-(k.a||k.ArrowLeft?1:0),z=move.current.z+(k.s||k.ArrowDown?1:0)-(k.w||k.ArrowUp?1:0);r.speed=Math.hypot(x,z)>0?7:0;tick(r,dt,{x,z});const sig=signal(r);if(r.round===0&&sig!==lastSignal.current&&r.status==='playing')beepRef.current(sig==='red'?180:700);lastSignal.current=sig;}
 elapsed+=dt;if(elapsed>0.07){setS({...r});elapsed=0;}});}catch{setError('3D 화면을 시작할 수 없습니다. 브라우저의 하드웨어 가속을 켜고 다시 시도해 주세요.');}
 const down=e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.current[e.key.toLowerCase().startsWith('arrow')?e.key:e.key.toLowerCase()]=true;if(e.key==='Escape'){pausedRef.current=!pausedRef.current;pause(pausedRef.current);}if(e.code==='Space'&&!e.repeat&&!pausedRef.current&&run.current.round===2)act(run.current,0);};const up=e=>{keys.current[e.key]=false;keys.current[e.key.toLowerCase()]=false;};const blur=()=>{keys.current={};move.current={x:0,z:0};if(run.current.status==='playing'){pausedRef.current=true;pause(true);}};
 window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{dispose?.();sound.current?.close();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};},[]);
 const toggle=()=>{pausedRef.current=!pausedRef.current;pause(pausedRef.current);keys.current={};move.current={x:0,z:0};};
 return <main className="arena"><div className="arena-world" ref={mount}/><div className="arena-vignette"/>
 <header className="arena-header"><a href="./" className="arena-brand">○ △ □ <span>THE ISLAND</span></a><div className="arena-tools"><button onClick={()=>mute(!muted)}>{muted?'소리 켜기':'소리 끄기'}</button><button onClick={toggle}>{paused?'계속':'일시정지'}</button><a href="./?mode=city">도시 모드 ↗</a></div></header>
 <aside className="arena-round"><span>PLAYER 456 / ROUND 0{s.round+1}</span><h1>{ROUNDS[s.round][0]}</h1><p>{ROUNDS[s.round][1]}</p></aside>
 <div className="arena-clock"><span>TIME REMAINING</span><strong>{Math.floor(Math.ceil(s.time)/60).toString().padStart(2,'0')}:{(Math.ceil(s.time)%60).toString().padStart(2,'0')}</strong><small>{s.practice?'연습 경기':'6 ROUND SURVIVAL'}</small></div>
 {s.status==='playing'&&!paused&&<>
 {s.round===0&&<div className={'arena-signal '+signal(s)}>{signal(s)==='green'?'전진하세요':signal(s)==='warning'?'곧 정지':'움직이지 마세요'}<small>{signal(s)==='warning'?`${(5.2-s.elapsed%7.6).toFixed(1)}초`:'무궁화꽃이 피었습니다'}</small></div>}
 {s.round===1&&<div className="arena-task"><p>설탕 뽑기 · {s.progress}/24 <span>균열 {s.mistakes}/3</span></p><svg viewBox="0 0 300 300" role="group" aria-label="설탕 뽑기" onPointerDown={e=>{if(e.target===e.currentTarget)action(-1);}}><circle cx="150" cy="150" r="143" fill="#bd7e30" onPointerDown={()=>action(-1)}/><circle cx="150" cy="150" r="100" fill="none" stroke="#714717" strokeWidth="3"/>{Array.from({length:24},(_,i)=>{const a=i/24*Math.PI*2;return <circle key={i} cx={150+Math.cos(a)*100} cy={150+Math.sin(a)*100} r="11" fill={i<s.progress?'#634822':i===s.progress?'#f7fff0':'#dbab60'} stroke={i===s.progress?'#fff':'#8e5d24'} strokeWidth="2" role="button" tabIndex={0} aria-label={`${i+1}번째 바늘 위치`} onKeyDown={e=>{if(e.key==='Enter')action(i);}} onPointerDown={()=>action(i)}/>;})}</svg><small>밝은 점부터 차례대로 누르세요</small></div>}
 {s.round===2&&<div className="arena-task"><h2>함께 당겨!</h2><p>우리 팀의 힘 {Math.round(s.force*100)}%</p><progress value={s.force} max="1"/><div className="arena-timing"><i/><b style={{left:`${50+Math.sin(s.elapsed*3)*46}%`}}/></div><button className="arena-primary" onClick={()=>action(0)}>당기기 · SPACE</button><p>{s.message}</p></div>}
 {s.round===3&&<div className="arena-task"><h2>깐부의 구슬</h2><div className="arena-marbles">{s.marbles}<small> / 20</small></div><p>상대가 쥔 구슬은 홀수일까요, 짝수일까요?</p><div className="arena-choice"><button onClick={()=>action(1)}>홀수</button><button onClick={()=>action(0)}>짝수</button></div><p>{s.message||'각자 10개로 시작 · 한 번에 2개'}</p></div>}
 {s.round===4&&<div className="arena-bridge"><p>{s.elapsed<4?`강화유리 위치를 기억하세요 · ${Math.ceil(4-s.elapsed)}`:`${s.progress} / 8 칸 통과`}</p><div className="arena-choice"><button disabled={s.elapsed<4} onClick={()=>action(0)}>↖ 왼쪽</button><button disabled={s.elapsed<4} onClick={()=>action(1)}>오른쪽 ↗</button></div></div>}
 {s.round===5&&<div className="arena-signal green">머리의 원에 도착하세요<small>체력 {Math.ceil(s.health)} · 수비수를 크게 돌아 피하세요</small></div>}
 {(s.round===0||s.round===5)&&<div className="arena-controls"><div className="arena-pad">{[['↑',0,-1],['←',-1,0],['↓',0,1],['→',1,0]].map(([label,x,z])=><button key={label} aria-label={`${label} 이동`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);move.current={x,z};}} onPointerUp={()=>move.current={x:0,z:0}} onPointerCancel={()=>move.current={x:0,z:0}}>{label}</button>)}</div><span>W A S D / 방향키 이동<br/>손을 떼면 즉시 정지</span></div>}
 </>}
 {(s.status!=='playing'||paused||error)&&<div className="arena-overlay"><section className="arena-panel"><span className="arena-eyebrow">{error?'DISPLAY ERROR':paused?'PAUSED':s.status==='lost'?'ELIMINATED':s.status==='won'?'ROUND COMPLETE':'WELCOME, PLAYER 456'}</span><h2>{error?'화면 연결 실패':paused?'잠시 숨을 고르세요':s.status==='lost'?'탈락했습니다':s.status==='won'?(s.round===5?'최후의 생존자':'다음 경기로'):<>여섯 번의 게임.<br/>단 한 명의 생존자.</>}</h2><p>{error|| (paused?'준비되면 경기를 계속하세요.':s.status==='ready'?ROUNDS[s.round][1]:s.message)}</p>
 {!error&&(paused?<button className="arena-primary" onClick={toggle}>계속하기</button>:s.status==='ready'?<button className="arena-primary" onClick={()=>{beep();run.current.status='playing';setS({...run.current});}}>0{s.round+1} 경기 시작 →</button>:s.status==='won'&&s.round<5&&!s.practice?<button className="arena-primary" onClick={()=>start(s.round+1)}>다음 경기 →</button>:<button className="arena-primary" onClick={()=>start(s.practice?s.round:0,s.practice)}>다시 도전 →</button>)}
 {s.status==='ready'&&!paused&&<><div className="arena-practice">{ROUNDS.map((r,i)=><button key={r[0]} onClick={()=>start(i,true)} className={s.round===i?'selected':''}>0{i+1} {r[0]}</button>)}</div><p className="arena-footnote">전체 도전은 <button onClick={()=>start(0,false)}>처음부터</button> · 각 경기를 선택하면 연습 모드<br/>시즌 1에서 영감받은 싱글플레이 각색 · GTA풍 독립 3D 게임</p></>}
 </section></div>}
 <footer className="arena-footer"><span>ISOLATED ZONE — 37° N</span><span>○ △ □</span><span>{s.practice?'PRACTICE':'SURVIVAL'} / 456</span></footer>
 </main>;
}
